language: java
jdk: oraclejdk8
dist: trusty
deploy:
  provider: heroku
  api_key:
    secure: q+gIhnVFuFHTwEWDCVPDEp3OHNvsj5LhTcl0pj1emV+yp2iEIX7Uoh8hwFgMreTSS/TsQYyNBsMxSu6GvR462h1+3W3CQ3S4QVLV2OrZR0hJxOJ6PoKb7hazYzxufdEk8FILrF70njVLVTh58rsZRuLC/mzw5B7mR1LOGcCmJsKOkXDgt7XtXcdyNkShqTYPeS/ipAzF6hUTmWddhofWobSKimYp9svj/o5g1I6nrfZh6wlq7qwmcBB33UNDHxiBvX+IEUGtSCHhl07Oo3w0n0bZDr7vXSpSZ171UygAIswgRg0n4OOoI6mIXqUjrBYSqmaSqm3IAlcLAwWeTLEEaoN/+PG9m+kR9Zy1mhJPtQxJQL19kbTfSN0Xa3VVYmJ57RNhMJyDb0mWhG0veOOY8Ihyk70XPRWT/eNWA95H/s6ESBDzDysDrtlvXOuNP1hEiZo9/0A6AMe4StFhSdVQWYhRCoD0+yDI+OrkF9tQBgLRrC4WJKvYn3a2k5iMCsRJngob25wgchDDrZnzJVkbfNPYjgKRT9HQXBSFqPLPLfI8EV7stVbUs3C+yXNY34XfhlJVhkeCMVQzFdoTFzG18tsHVJN0KbUUnID/oUAnYFG3H6V5Fr7xiM0Kn0+qLJZo4J4mI5CYpCH03YUOKP05L+v045l0mGGHU1Vt0Xx9kBs=
  app: isapi-graphics
